name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm install -g @nrwl/cli
      - run: npm install --save-dev @swc-node/register @swc/core  # Add SWC dependencies
      - run: npm install --save-dev @nx/webpack webpack-cli  # Add webpack dependencies
      - run: npx nx run-many -t build
      - run: npx nx run-many -t test
