name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      
      # Install dependencies in stages
      - run: npm cache clean --force
      - run: rm -rf node_modules
      - run: npm install --legacy-peer-deps  # Base install
      - run: npm install -g nx@latest  # Latest stable version
      
      # Install dev dependencies separately
      - run: npm install --save-dev @swc-node/register @swc/core
      - run: npm install --save-dev @nx/webpack webpack-cli
      - run: npm install --save-dev @nx/eslint-plugin eslint-plugin-playwright
      - run: npm install --save-dev @playwright/test jest jest-environment-jsdom
      - run: npm install --save-dev @nx/jest @nx/react @nx/eslint @nx/playwright
      - run: npm install --save-dev typescript-eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
      - run: npm install --save-dev eslint ts-jest
      - run: npm install --save-dev eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-jsx-a11y

      # Build for production
      - run: npx nx build hatch_project --prod
      
      # Optional: Run tests before deploying
      - run: npx nx test hatch_project
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/hatch_project