name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      
      # Clean up existing workspace
      - run: |
          echo "Cleaning up workspace..."
          rm -rf hatch-project
          rm -rf apps
          rm -f nx.json
          rm -f package.json
          rm -f package-lock.json
      
      # Create temporary directory for the new workspace
      - run: |
          echo "Creating temporary directory..."
          mkdir -p /tmp/nx-workspace
          cd /tmp/nx-workspace
          
          echo "Creating new Nx workspace..."
          npx create-nx-workspace@latest . \
            --preset=react-monorepo \
            --appName=hatch_project \
            --style=css \
            --nxCloud=skip \
            --packageManager=npm \
            --no-interactive \
            --defaultBase=main
          
          echo "Workspace contents:"
          ls -la
          
          echo "Copying workspace files back..."
          cd $GITHUB_WORKSPACE
          cp -r /tmp/nx-workspace/* .
          cp -r /tmp/nx-workspace/.* . 2>/dev/null || true
      
      # Configure base URL for GitHub Pages
      - run: |
          echo "Configuring base URL..."
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
          echo "Base URL will be: /$REPO_NAME/"
          
          # Update vite.config.ts
          cat > apps/hatch_project/vite.config.ts << EOF
          /// <reference types='vitest' />
          import { defineConfig } from 'vite';
          import react from '@vitejs/plugin-react';
          import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';

          export default defineConfig({
            root: __dirname,
            base: '/$REPO_NAME/',
            cacheDir: '../../node_modules/.vite/hatch_project',

            plugins: [react(), nxViteTsPaths()],

            build: {
              outDir: '../../dist/apps/hatch_project',
              emptyOutDir: true,
              reportCompressedSize: true,
              commonjsOptions: { transformMixedEsModules: true },
            },

            test: {
              globals: true,
              cache: {
                dir: '../../node_modules/.vitest',
              },
              environment: 'jsdom',
              include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
            },
          });
          EOF
      
      # Build for production
      - run: |
          echo "Running build command..."
          npx nx build hatch_project --configuration=production --verbose
      
      # Debug: Show build output
      - run: |
          echo "Build output structure:"
          ls -R dist/ || true
          
          echo "Looking for build files:"
          find . -type f \( \
            -name "*.js" -o \
            -name "*.html" -o \
            -name "*.css" -o \
            -name "*.json" -o \
            -name "*.ico" -o \
            -name "*.png" -o \
            -name "*.svg" \
          \) -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./dist/*"
          
          echo "Contents of apps/hatch_project:"
          ls -la apps/hatch_project/
          
          echo "Contents of dist directory (if exists):"
          ls -la dist/ || true
      
      # Create deployment directory and copy files
      - run: |
          echo "Setting up deployment directory..."
          mkdir -p dist/apps/hatch_project
          
          echo "Looking for build output in possible locations..."
          for dir in dist/hatch_project dist/apps/hatch_project apps/hatch_project/dist; do
            if [ -d "$dir" ] && [ -n "$(ls -A $dir)" ]; then
              echo "Found build files in $dir"
              cp -r $dir/* dist/apps/hatch_project/
              break
            fi
          done
          
          echo "Final deployment directory contents:"
          ls -la dist/apps/hatch_project/
      
      # Verify deployment directory
      - run: |
          echo "Verifying deployment directory..."
          if [ ! -f "dist/apps/hatch_project/index.html" ]; then
            echo "Error: index.html not found in deployment directory!"
            exit 1
          fi
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/hatch_project
          enable_jekyll: false
          keep_files: false
          force_orphan: true